### PR TITLE
Simplify and fix sorting options

### LINKED ISSUE #530: Sort by size doesn't put folders first
image

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The result is smaller code that's easier to understand.  This also fixes sorting of directories before files when sorting by size.

Fixes #530

### CODE REVIEW

File: src/files-card-body.jsx [hunk 1]
```diff
@@ -42,42 +42,23 @@ import "./files-card-body.scss";
...
-        const aIsDir = (a.type === "dir" || a?.to === "dir");
-        const bIsDir = (b.type === "dir" || b?.to === "dir");
-
-        if (aIsDir && !bIsDir)
-            return -1;
-        if (!aIsDir && bIsDir)
-            return 1;
-        return 0;
+    const dir_sort = (a, b) => {
+        return Number(b.to === "dir") - Number(a.to === "dir");
```
Comment (martinpitt) [inline src/files-card-body.jsx:46]: I've stared at this for a while, and it feels like the wrong way around? If `b` is a dir and `a` is a file, then this would return 1, meaning that b > a, meaning that the file a sorts before dir b.

Can we have a test for the sort order?

**Comment by martinpitt** [comment]
#525 adds a test, but it pins down the wrong behaviour (not sorting dirs before files). Let's merge these two

File: src/files-card-body.jsx (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/files-card-body.jsx:46]: I also originally had it the other way.  I reversed it after manually testing it.

It could use a test in any case...

Comment (martinpitt) [reply src/files-card-body.jsx:46]: Sorry, I was wrong -- it returns 1, but that means that a > b.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Review by jelly — APPROVED** [review]
